
name: Deploy application

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Validate composer.json and composer.lock
            run: composer validate --strict

            - name: Cache Composer packages
            id: composer-cache
            uses: actions/cache@v3
            with:
                path: vendor
                key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                ${{ runner.os }}-php-

            - name: Install dependencies
            run: composer install --prefer-dist --no-progress
            - name: Run build script
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.IP_SERVER}}
                  username: ${{secrets.USERNAME}}
                  key: ${{secrets.SECRET_KEY}}
                  port: 22
                  script: |
                      cd /var/www/html/wp-content/themes/perfect-onderwijs-match/
                      git pull
                      cd
                      systemctl restart apache2.service
