name: PHP Composer

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: SSH Remote Commands
              uses: appleboy/ssh-action@v0.1.4
              with:
                  # ssh host
                  host: ${{secrets.IP_SERVER}}
                  # ssh port
                  port: ${{secrets.PORT}}
                  # ssh username
                  username: ${{secrets.USERNAME}}
                  # ssh password
                  key: ${{secrets.SECRET_KEY}}
                  passphrase: ${{secrets.PASS}}
                  script: |
                      cd /www/sebastianl42.sg-host.com/public_html/wp-content/themes/perfect-onderwijs-match
                      pwd
                      git pull git@github.com:SebastianLomme/perfect-onderwijs-match.git
                      pwd
                      ls
